INSERT INTO municipios(MUNICIPIO) VALUES ("Abasolo");
INSERT INTO municipios(MUNICIPIO) VALUES ("Acuña");
INSERT INTO municipios(MUNICIPIO) VALUES ("Allende");
INSERT INTO municipios(MUNICIPIO) VALUES ("Arteaga");
INSERT INTO municipios(MUNICIPIO) VALUES ("Candela");
INSERT INTO municipios(MUNICIPIO) VALUES ("Castaños");
INSERT INTO municipios(MUNICIPIO) VALUES ("Cuatro Ciénegas");
INSERT INTO municipios(MUNICIPIO) VALUES ("Escobedo");
INSERT INTO municipios(MUNICIPIO) VALUES ("Francisco I. Madero");
INSERT INTO municipios(MUNICIPIO) VALUES ("Frontera");
INSERT INTO municipios(MUNICIPIO) VALUES ("General Cepeda");
INSERT INTO municipios(MUNICIPIO) VALUES ("Guerrero");
INSERT INTO municipios(MUNICIPIO) VALUES ("Hidalgo");
INSERT INTO municipios(MUNICIPIO) VALUES ("Jiménez");
INSERT INTO municipios(MUNICIPIO) VALUES ("Juárez");
INSERT INTO municipios(MUNICIPIO) VALUES ("Lamadrid");
INSERT INTO municipios(MUNICIPIO) VALUES ("Matamoros");
INSERT INTO municipios(MUNICIPIO) VALUES ("Monclova");
INSERT INTO municipios(MUNICIPIO) VALUES ("Morelos");
INSERT INTO municipios(MUNICIPIO) VALUES ("Múzquiz");
INSERT INTO municipios(MUNICIPIO) VALUES ("Nadadores");
INSERT INTO municipios(MUNICIPIO) VALUES ("Nava");
INSERT INTO municipios(MUNICIPIO) VALUES ("Ocampo");
INSERT INTO municipios(MUNICIPIO) VALUES ("Parras");
INSERT INTO municipios(MUNICIPIO) VALUES ("Piedras Negras");
INSERT INTO municipios(MUNICIPIO) VALUES ("Progreso");
INSERT INTO municipios(MUNICIPIO) VALUES ("Ramos Arizpe");
INSERT INTO municipios(MUNICIPIO) VALUES ("Sabinas");
INSERT INTO municipios(MUNICIPIO) VALUES ("Sacramento");
INSERT INTO municipios(MUNICIPIO) VALUES ("Saltillo");
INSERT INTO municipios(MUNICIPIO) VALUES ("San Buenaventura");
INSERT INTO municipios(MUNICIPIO) VALUES ("San Juan de Sabinas");
INSERT INTO municipios(MUNICIPIO) VALUES ("San Pedro");
INSERT INTO municipios(MUNICIPIO) VALUES ("Sierra Mojada");
INSERT INTO municipios(MUNICIPIO) VALUES ("Torreón");
INSERT INTO municipios(MUNICIPIO) VALUES ("Viesca");
INSERT INTO municipios(MUNICIPIO) VALUES ("Villa Unión");
INSERT INTO municipios(MUNICIPIO) VALUES ("Zaragoza");

INSERT INTO asunto (ASUNTO) VALUES ("Distancia");
INSERT INTO asunto (ASUNTO) VALUES ("Registro");
INSERT INTO asunto (ASUNTO) VALUES ("Baja");
INSERT INTO asunto (ASUNTO) VALUES ("Cambio de institución");
INSERT INTO asunto (ASUNTO) VALUES ("Asunto adicional 4 the win");

INSERT INTO usuarios (USER, PASS, is_admin)VALUES("hiro","$2y$10$VFc5f7DAbCVRCvEhahqzWeYKbz15Fk35Kp4UupBP3.jfkdnV9mVoe",1);
INSERT INTO usuarios (USER, PASS, is_admin)VALUES("lucely","$2y$10$hKT76hTnXFsh7uqBNeKP2Oywl7Lk8L33G8xrWDVoYpEJziAV1Fbsq",1);
INSERT INTO usuarios (USER, PASS, is_admin)VALUES("cris","$2y$10$hL8I3R952u.Uh.Q1NAuvs..ay.BiYXINaV2DIwgjEUQh4N5O/BFm2",1);
INSERT INTO usuarios (USER, PASS, is_admin)VALUES("mortal1","$2y$10$tu4DlPfkWF4c89Ou3DsBUO5cmeHgPEaHYkJP23QRSHro1NfbrIdbG",0);
INSERT INTO usuarios (USER, PASS, is_admin)VALUES("mortal2","$2y$10$HdAcak5N634o9ib2IoSni.45REfR2Y2ih1r6AvbyotDGhEoiq/k8u",0);
INSERT INTO usuarios (USER, PASS, is_admin)VALUES("mortal3","$2y$10$z4uJGj5vjPjiHRWTSgVmCeIl7Uo2x9xWV2qhjg36MoBymZmJc6wtG",0);